# Generated by Django 4.0.4 on 2022-05-24 12:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_image_post_file_1_post_file_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
