# Generated by Django 4.0.4 on 2022-05-24 13:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_file_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_2',
            field=models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='file_3',
            field=models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='file_4',
            field=models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='file_5',
            field=models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
