# Generated by Django 4.0.4 on 2022-05-26 09:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_file_2_alter_post_file_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
