# Generated by Django 4.0.4 on 2022-05-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
